
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Sun Apr 28 21:50:39 CEST 2019
//----------------------------------------------------

package constructorast;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int PCIERRE = 6;
  public static final int MENOS = 18;
  public static final int AND = 15;
  public static final int MENOR = 11;
  public static final int OR = 16;
  public static final int IGUAL = 7;
  public static final int MAYIGUAL = 12;
  public static final int NOT = 17;
  public static final int IDEN = 2;
  public static final int TRUE = 25;
  public static final int POR = 19;
  public static final int NUM = 23;
  public static final int SEPARADOR = 21;
  public static final int MENIGUAL = 13;
  public static final int MAYOR = 10;
  public static final int EOF = 0;
  public static final int DIFERENTE = 22;
  public static final int DIV = 20;
  public static final int PAP = 5;
  public static final int FALSE = 26;
  public static final int error = 1;
  public static final int EQUIVALENTE = 8;
  public static final int BOOL = 24;
  public static final int PUNTOCOMA = 9;
  public static final int REAL = 4;
  public static final int ENT = 3;
  public static final int MAS = 14;
}

