/* Generated By:JavaCC: Do not edit this line. ConstructorASTConstants.java */
package constructorast;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ConstructorASTConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int letra = 1;
  /** RegularExpression Id. */
  int digito = 2;
  /** RegularExpression Id. */
  int bbaja = 3;
  /** RegularExpression Id. */
  int num = 5;
  /** RegularExpression Id. */
  int bool = 6;
  /** RegularExpression Id. */
  int verdadero = 7;
  /** RegularExpression Id. */
  int falso = 8;
  /** RegularExpression Id. */
  int or = 9;
  /** RegularExpression Id. */
  int and = 10;
  /** RegularExpression Id. */
  int not = 11;
  /** RegularExpression Id. */
  int separador = 12;
  /** RegularExpression Id. */
  int exponencial = 13;
  /** RegularExpression Id. */
  int identificador = 14;
  /** RegularExpression Id. */
  int numeroEntero = 15;
  /** RegularExpression Id. */
  int numeroReal = 16;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<letra>",
    "<digito>",
    "\"_\"",
    "<token of kind 4>",
    "\"num\"",
    "\"bool\"",
    "\"true\"",
    "\"false\"",
    "\"or\"",
    "\"and\"",
    "\"not\"",
    "\"&&\"",
    "<exponencial>",
    "<identificador>",
    "<numeroEntero>",
    "<numeroReal>",
    "\";\"",
    "\"=\"",
    "\"-\"",
    "\"(\"",
    "\")\"",
    "\"+\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"==\"",
    "\"!=\"",
    "\"*\"",
    "\"/\"",
  };

}
